name: Publish to TestPyPI

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

on:
  workflow_dispatch:

jobs:
  publish-testpypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    environment:
      name: testpypi

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Build package
        run: uv build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
